In [11]:

import tensorflow as tf

## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]



In [12]:
## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
import math
print(math.sqrt(1))
W= tf.Variable( tf.random.normal((1,1), mean=0, stddev=1))#tf.sqrt(1)) )  
b= tf.Variable( tf.random.normal((1,1), mean=0, stddev=1))#tf.sqrt(1)) )
print("W : ", W)
print("b : ", b)



1.0
W :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.65887684]], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.74788976]], dtype=float32)>


In [37]:
W= tf.Variable( tf.random.normal((1,1), mean=0, stddev=1))#tf.sqrt(1)) )  
b= tf.Variable( tf.random.normal((1,1), mean=0, stddev=1))#tf.sqrt(1)) )
err = 0.
for i in range(1, 50):
    for j in range(len(x_data)):
        ## data * weight 작성
        WX = tf.matmul([x_data[j]], W)

        ## bias add 작성
        y_hat = tf.add(WX, b)

        ## W와 b로 예측 하기
        print("y_data: , ", y_data[j], "prediction : ", y_hat)
        err = (((y_data[j]-y_hat)))*0.3
        print("error : ", err)
        W = tf.subtract(W, err)
        b = tf.subtract(b, err*0.3*x_data[j])
        print("W : ", W)
        #if err == 0. :
        #    break
    #if err == 0.:
    #    break

y_data: ,  [1.0] prediction :  tf.Tensor([[0.1552997]], shape=(1, 1), dtype=float32)
error :  tf.Tensor([[0.2534101]], shape=(1, 1), dtype=float32)
W :  tf.Tensor([[-0.5267001]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[-0.70083356]], shape=(1, 1), dtype=float32)
error :  tf.Tensor([[1.1102501]], shape=(1, 1), dtype=float32)
W :  tf.Tensor([[-1.6369503]], shape=(1, 1), dtype=float32)
y_data: ,  [5.0] prediction :  tf.Tensor([[-5.224434]], shape=(1, 1), dtype=float32)
error :  tf.Tensor([[3.0673304]], shape=(1, 1), dtype=float32)
W :  tf.Tensor([[-4.704281]], shape=(1, 1), dtype=float32)
y_data: ,  [7.0] prediction :  tf.Tensor([[-21.891304]], shape=(1, 1), dtype=float32)
error :  tf.Tensor([[8.667392]], shape=(1, 1), dtype=float32)
W :  tf.Tensor([[-13.371673]], shape=(1, 1), dtype=float32)
y_data: ,  [1.0] prediction :  tf.Tensor([[-26.846724]], shape=(1, 1), dtype=float32)
error :  tf.Tensor([[8.354017]], shape=(1, 1), dtype=float32)
W :  tf.Tensor([[-2