In [1]:

import tensorflow as tf

## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]



In [39]:

## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
b=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
lr=tf.constant(0.01)


In [40]:

for i in range(2000):  ## 에폭
    total_error = 0

    for j in range(len(x_data)): ## 배치 1
        ## data * weight
        WX =tf.matmul([x_data[j]], W)

        ## bias add
        y_hat = tf.add(WX, b)

        ## 정답인 Y와 출력값의 error 계산
        error = tf.subtract(y_data[j], y_hat)
        #error = tf.subtract([y_data[j]], y_hat)

        ## 경사하강법으로 W와 b 업데이트.
        ## 도함수 구하기
        diff_W = tf.matmul(error, [x_data[j]])
        diff_b = error

        ##  업데이트할 만큼 러닝레이트 곱
        ## 중요 multiply로 곱해야함...
        diff_W = tf.multiply(diff_W, lr)
        diff_b = tf.multiply(diff_b, lr)

        ## w, b 업데이트
        W = tf.add(W, diff_W)
        b = tf.add(b, diff_b)
        #######

        ## 토탈 에러.
        total_error = total_error + tf.square(error)

    ## 모든 데이터에 따른 error 값
    print("epoch: ", i, "error : ", total_error/len(x_data))


epoch:  0 error :  tf.Tensor([[56.592667]], shape=(1, 1), dtype=float32)
epoch:  1 error :  tf.Tensor([[27.902992]], shape=(1, 1), dtype=float32)
epoch:  2 error :  tf.Tensor([[13.893615]], shape=(1, 1), dtype=float32)
epoch:  3 error :  tf.Tensor([[7.0595083]], shape=(1, 1), dtype=float32)
epoch:  4 error :  tf.Tensor([[3.7298036]], shape=(1, 1), dtype=float32)
epoch:  5 error :  tf.Tensor([[2.1098075]], shape=(1, 1), dtype=float32)
epoch:  6 error :  tf.Tensor([[1.3226597]], shape=(1, 1), dtype=float32)
epoch:  7 error :  tf.Tensor([[0.94033235]], shape=(1, 1), dtype=float32)
epoch:  8 error :  tf.Tensor([[0.7541642]], shape=(1, 1), dtype=float32)
epoch:  9 error :  tf.Tensor([[0.66262627]], shape=(1, 1), dtype=float32)
epoch:  10 error :  tf.Tensor([[0.6164514]], shape=(1, 1), dtype=float32)
epoch:  11 error :  tf.Tensor([[0.5918245]], shape=(1, 1), dtype=float32)
epoch:  12 error :  tf.Tensor([[0.5772997]], shape=(1, 1), dtype=float32)
epoch:  13 error :  tf.Tensor([[0.56742346]], 

In [41]:

## 학습끝난 후 W와 b로 예측 하기
print("W : ", W)
print("b : ", b)
print("input 3 : ", tf.add(tf.multiply(3, W), b))
print("input 4 : ", tf.add(tf.multiply(4, W), b))
print("input 5 : ", tf.add(tf.multiply(5, W), b))

W :  tf.Tensor([[1.9999964]], shape=(1, 1), dtype=float32)
b :  tf.Tensor([[-0.99998957]], shape=(1, 1), dtype=float32)
input 3 :  tf.Tensor([[5.]], shape=(1, 1), dtype=float32)
input 4 :  tf.Tensor([[6.999996]], shape=(1, 1), dtype=float32)
input 5 :  tf.Tensor([[8.999992]], shape=(1, 1), dtype=float32)
