In [1]:

import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import LabelEncoder
import numpy as np




In [3]:
# 데이터 입력
df = pd.read_csv('../dataset/one_hot_encording_test.csv', names = ["length", "width", "height", "volume", "class_name"])
dataset=df.copy()



In [4]:
Y_obj = dataset.pop("class_name")
X = dataset.copy()
print("data value : {}".format(X))
print("data Label: {}".format(Y_obj))



data value :     length  width  height  volume
0      5.1    0.5     1.4    0.02
1      4.9    0.2     1.4    0.03
2      4.7    0.2     1.3    0.04
3      4.6    0.1     1.5    0.05
4      5.0    0.6     1.4    0.02
5      5.4    0.9     1.7    0.03
6      4.6    0.4     1.4    0.33
7      5.0    0.4     1.5    0.12
8      4.4    0.9     1.4    0.12
9      3.9    0.1     1.5    0.21
10     2.2    0.5     1.4    0.03
11     4.2    0.0     1.4    0.02
12     5.1    0.2     1.3    0.05
13     4.2    0.1     1.5    0.06
14     2.0    0.6     1.4    0.07
15     4.4    0.9     1.7    0.08
16     7.6    0.4     1.4    0.02
17     8.0    0.4     1.5    0.09
18     6.4    0.9     1.4    0.04
19     5.9    0.1     1.5    0.02
data Label: 0        car
1        car
2        car
3      truck
4      truck
5      truck
6        bus
7     person
8     person
9        bus
10       car
11       car
12       car
13     truck
14     truck
15     truck
16       bus
17    person
18    person
19       bus
N

In [5]:
# case 1)
# Label Encoder는 독립 변수가 아닌 종속 변수(라벨)에 대해 사용한다. 문자열이나 정수로된 라벨 값을  0  ~  K−1 까지의 정수로 변환.
e = LabelEncoder()
e.fit(Y_obj)
print("Label Class String : {}".format(e.classes_))
Y = e.transform(Y_obj)
print("Label Class Int: {}".format(Y))

Y_encoded = tf.keras.utils.to_categorical(Y)
print("case 1 One Hot Label Class : {}".format(Y_encoded))
print(np.argmax(Y_encoded, axis=1).reshape(-1,1))
print(Y_encoded.shape)



Label Class String : ['bus' 'car' 'person' 'truck']
Label Class Int: [1 1 1 3 3 3 0 2 2 0 1 1 1 3 3 3 0 2 2 0]
case 1 One Hot Label Class : [[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]
[[1]
 [1]
 [1]
 [3]
 [3]
 [3]
 [0]
 [2]
 [2]
 [0]
 [1]
 [1]
 [1]
 [3]
 [3]
 [3]
 [0]
 [2]
 [2]
 [0]]
(20, 4)


In [7]:
## case 2)
one_hot_label=pd.get_dummies(Y_obj)
print("case 2 one_hot_label : ", one_hot_label)
print(one_hot_label.shape)
print(one_hot_label.values)

case 2 one_hot_label :      bus  car  person  truck
0     0    1       0      0
1     0    1       0      0
2     0    1       0      0
3     0    0       0      1
4     0    0       0      1
5     0    0       0      1
6     1    0       0      0
7     0    0       1      0
8     0    0       1      0
9     1    0       0      0
10    0    1       0      0
11    0    1       0      0
12    0    1       0      0
13    0    0       0      1
14    0    0       0      1
15    0    0       0      1
16    1    0       0      0
17    0    0       1      0
18    0    0       1      0
19    1    0       0      0
(20, 4)
[[0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 1 0 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 1]
 [1 0 0 0]
 [0 0 1 0]
 [0 0 1 0]
 [1 0 0 0]]
