In [13]:

import tensorflow as tf

## data 선언
x_data =[[1.],[2.],[3.]] # input data
y_data =[[1.],[2.],[3.]] # label -> 결과값... 

print(y_data)

## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1), mean=1, stddev=0.5))
b=tf.Variable(tf.random.normal((1,1), mean=1, stddev=0.5))
print("W : ", W)
print("b : ", b)
print("{}".format(b[0]))


[[1.0], [2.0], [3.0]]
W :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[1.3841503]], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[1.0573332]], dtype=float32)>
[1.0573332]


In [5]:
for j in range(len(x_data)):
    ## data * weight
    WX =tf.matmul([x_data[j]], W)

    ## bias add
    y_hat = tf.add(WX, b)

    ## W와 b로 예측 하기
    print("y_data: , ",y_data[j], "prediction : ", y_hat)

y_data: ,  [1.0] prediction :  tf.Tensor([[0.7647395]], shape=(1, 1), dtype=float32)
y_data: ,  [2.0] prediction :  tf.Tensor([[1.3347445]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[1.9047494]], shape=(1, 1), dtype=float32)
