In [1]:

import tensorflow as tf

## data 선언
x_data =[[1.],[2.],[3.]]
y_data =[[1.],[2.],[3.]]

## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1), mean=1, stddev=0.5))
b=tf.Variable(tf.random.normal((1,1), mean=1, stddev=0.5))
print("W : ", W)
print("b : ", b)


W :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.71415496]], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.57918787]], dtype=float32)>
y_data: ,  [1.0] prediction :  tf.Tensor([[1.2933428]], shape=(1, 1), dtype=float32)
y_data: ,  [2.0] prediction :  tf.Tensor([[2.0074978]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[2.7216527]], shape=(1, 1), dtype=float32)


In [2]:
for j in range(len(x_data)):
    ## data * weight
    WX =tf.matmul([x_data[j]], W)

    ## bias add
    y_hat = tf.add(WX, b)

    ## W와 b로 예측 하기
    print("y_data: , ",y_data[j], "prediction : ", y_hat)

y_data: ,  [1.0] prediction :  tf.Tensor([[1.2933428]], shape=(1, 1), dtype=float32)
y_data: ,  [2.0] prediction :  tf.Tensor([[2.0074978]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[2.7216527]], shape=(1, 1), dtype=float32)
