In [2]:

import tensorflow as tf

## data 선언
x_data =[[1.],[2.],[3.],[4.]]
y_data =[[1.],[3.],[5.],[7.]]


In [3]:

## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
b=tf.Variable(tf.random.normal((1,1),mean=0, stddev=1.0))
lr=tf.constant(0.01)


In [4]:

for i in range(2000):  ## 에폭
    total_error = 0

    for j in range(len(x_data)): ## 배치 1
        ## data * weight
        WX =tf.matmul([x_data[j]], W)

        ## bias add
        y_hat = tf.add(WX, b)

        ## 정답인 Y와 출력값의 error 계산
        error = tf.subtract(y_data[j], y_hat) ## (true - prediction)


        ## 경사하강법으로 W와 b 업데이트.
        ## 도함수 구하기
        diff_W = tf.matmul(error,[x_data[j]])#error*x의 합
        diff_b = error

        ##  업데이트할 만큼 러닝레이트 곱
        diff_W = tf.multiply(lr, diff_W)
        diff_b = tf.multiply(lr, diff_b)  #  lr * (error)

        ## w, b 업데이트
        W=tf.add(W, diff_W) # w + lr * x * (error)
        b=tf.add(b, diff_b) # b + lr * (error)
        #######

        ## 토탈 에러.
        visual_error=tf.square(error)
        total_error = total_error + visual_error

    ## 모든 데이터에 따른 error 값
    print("epoch: ", i, "error : ", total_error/len(x_data))


epoch:  0 error :  tf.Tensor([[5.681863]], shape=(1, 1), dtype=float32)
epoch:  1 error :  tf.Tensor([[3.3442082]], shape=(1, 1), dtype=float32)
epoch:  2 error :  tf.Tensor([[2.2087522]], shape=(1, 1), dtype=float32)
epoch:  3 error :  tf.Tensor([[1.6569505]], shape=(1, 1), dtype=float32)
epoch:  4 error :  tf.Tensor([[1.3874853]], shape=(1, 1), dtype=float32)
epoch:  5 error :  tf.Tensor([[1.2538941]], shape=(1, 1), dtype=float32)
epoch:  6 error :  tf.Tensor([[1.185209]], shape=(1, 1), dtype=float32)
epoch:  7 error :  tf.Tensor([[1.1472032]], shape=(1, 1), dtype=float32)
epoch:  8 error :  tf.Tensor([[1.1234771]], shape=(1, 1), dtype=float32)
epoch:  9 error :  tf.Tensor([[1.1062527]], shape=(1, 1), dtype=float32)
epoch:  10 error :  tf.Tensor([[1.0918967]], shape=(1, 1), dtype=float32)
epoch:  11 error :  tf.Tensor([[1.0787499]], shape=(1, 1), dtype=float32)
epoch:  12 error :  tf.Tensor([[1.066084]], shape=(1, 1), dtype=float32)
epoch:  13 error :  tf.Tensor([[1.0536003]], shape=

In [6]:

## 학습끝난 후 W와 b로 예측 하기
print("W : ", W)
print("b : ", b)
print("input 3 : ", tf.add(tf.multiply(3, W), b))
print("input 5 : ", tf.add(tf.multiply(5, W), b))


W :  tf.Tensor([[1.9999957]], shape=(1, 1), dtype=float32)
b :  tf.Tensor([[-0.9999881]], shape=(1, 1), dtype=float32)
input 3 :  tf.Tensor([[4.999999]], shape=(1, 1), dtype=float32)
input 5 :  tf.Tensor([[8.99999]], shape=(1, 1), dtype=float32)
