In [1]:

import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import LabelEncoder

# 데이터 입력
df = pd.read_csv('../dataset/one_hot_encording_test2.csv', names = ["length", "width", "height", "class_name"])






In [6]:
# # 데이터 분류
dataset = df.copy()
#X = dataset[:, :3]
Y_obj = dataset.pop('class_name')
X = dataset#.values[:, :3]
print("data value : {}".format(X))
print("data Label: {}".format(Y_obj))




data value :    length  width  height
0     5.1    3.5     1.4
1     4.9    3.0     1.4
2     4.7    3.2     1.3
3     4.6    3.1     1.5
4     5.0    3.6     1.4
5     5.4    3.9     1.7
6     4.6    3.4     1.4
7     5.0    3.4     1.5
8     4.4    2.9     1.4
9     4.9    3.1     1.5
data Label: 0       car
1       car
2       car
3     truck
4     truck
5     truck
6       bus
7    person
8    person
9       bus
Name: class_name, dtype: object


In [8]:
# case 1)
# 문자열을 숫자로 변환
# Label Encoder는 독립 변수가 아닌 종속 변수(라벨)에 대해 사용한다. 문자열이나 정수로된 라벨 값을  0  ~  K−1 까지의 정수로 변환.
e = LabelEncoder()
e.fit(Y_obj)
print("Label Class String : {}".format(e.classes_))
Y = e.transform(Y_obj)
print("Label Class Int: {}".format(Y))

Y_encoded = tf.keras.utils.to_categorical(Y)
print("One Hot Label Class : {}".format(Y_encoded))




Label Class String : ['bus' 'car' 'person' 'truck']
Label Class Int: [1 1 1 3 3 3 0 2 2 0]
One Hot Label Class : [[0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [9]:
## case 2)
one_hot_label=pd.get_dummies(Y_obj)
print("case 2 one_hot_label : ", one_hot_label)
print(one_hot_label.shape)

case 2 one_hot_label :     bus  car  person  truck
0    0    1       0      0
1    0    1       0      0
2    0    1       0      0
3    0    0       0      1
4    0    0       0      1
5    0    0       0      1
6    1    0       0      0
7    0    0       1      0
8    0    0       1      0
9    1    0       0      0
(10, 4)
