In [10]:


import tensorflow as tf
from sklearn.model_selection import train_test_split
import os
import pandas as pd

gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
  try:
    # Currently, memory growth needs to be the same across GPUs
    for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
    logical_gpus = tf.config.experimental.list_logical_devices('GPU')
    print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPUs")
  except RuntimeError as e:
    # Memory growth must be set before GPUs have been initialized
    print(e)

data_dir = '../dataset'
fname = os.path.join(data_dir, 'data-02-stock_daily.csv')



1 Physical GPUs, 1 Logical GPUs


In [11]:
## 데이터 읽어오기.
df = pd.read_csv(fname)
dataset = df.values
ori_X = dataset[:,0:4]
ori_Y = dataset[:,4]

print(dataset.shape)
print(ori_X)
print(ori_Y)

(732, 5)
[[8.28659973e+02 8.33450012e+02 8.28349976e+02 1.24770000e+06]
 [8.23020020e+02 8.28070007e+02 8.21655029e+02 1.59780000e+06]
 [8.19929993e+02 8.24400024e+02 8.18979980e+02 1.28170000e+06]
 ...
 [5.66892592e+02 5.67002574e+02 5.56932537e+02 1.08000000e+04]
 [5.61202549e+02 5.66432590e+02 5.58672539e+02 4.12000000e+04]
 [5.68002570e+02 5.68002570e+02 5.52922516e+02 1.31000000e+04]]
[831.659973 828.070007 824.159973 818.97998  820.450012 819.23999
 813.669983 809.559998 808.380005 806.969971 801.340027 801.48999
 798.530029 795.695007 796.789978 802.320007 823.309998 832.150024
 835.669983 823.869995 819.309998 805.02002  802.174988 806.070007
 804.609985 807.880005 806.359985 807.909973 804.789978 806.650024
 806.150024 794.02002  786.900024 786.140015 771.820007 782.789978
 785.049988 791.549988 789.909973 791.26001  794.559998 796.419983
 794.200012 790.799988 797.849976 797.070007 796.099976 789.27002
 789.289978 776.419983 771.190002 759.109985 762.52002  750.5
 747.919983 

In [24]:
seq_length=8
X_train, X_test, Y_train, Y_test = train_test_split(ori_X,ori_Y, test_size=0.2, shuffle=False)
data_gen=tf.keras.preprocessing.sequence.TimeseriesGenerator(X_train, Y_train,
                               length=seq_length, sampling_rate=2,stride=8,
                               batch_size=1,
                               start_index=0,reverse=False) #reverse=False 순차적, TRUE는 역순:과거데이터를 먼저 넣는 모델을 만든다.


In [25]:
print(len(data_gen))
for i in range(2):
    x, y = data_gen[i]
    print(x, y)

73
[[[8.28659973e+02 8.33450012e+02 8.28349976e+02 1.24770000e+06]
  [8.19929993e+02 8.24400024e+02 8.18979980e+02 1.28170000e+06]
  [8.19000000e+02 8.23000000e+02 8.16000000e+02 1.05360000e+06]
  [8.11700012e+02 8.15250000e+02 8.09780029e+02 1.12910000e+06]]] [808.380005]
[[[8.07000000e+02 8.11840027e+02 8.03190002e+02 1.15530000e+06]
  [7.99700012e+02 8.01669983e+02 7.95250000e+02 1.17420000e+06]
  [7.93799988e+02 8.02700012e+02 7.92000000e+02 1.52580000e+06]
  [7.96859985e+02 8.01250000e+02 7.90520020e+02 2.14350000e+06]]] [823.309998]
